package cs5204.fs.common;

public enum Protocol
{
	CM_HANDSHAKE_REQUEST,
	CM_HANDSHAKE_RESPONSE,
	CM_OPERATION_REQUEST,
	CM_OPERATION_RESPONSE,
	CM_FOOTSHAKE_REQUEST,
	CM_FOOTSHAKE_RESPONSE,
	CM_RECOVERY_REQUEST,
	CM_RECOVERY_RESPONSE,
	MS_HANDSHAKE_REQUEST,
	MS_HANDSHAKE_RESPONSE,
	MS_COMMIT_REQUEST,
	MS_COMMIT_RESPONSE,
	MS_RECOVERY_REQUEST,
	MS_RECOVERY_RESPONSE,
	CS_OPERATION_REQUEST,
	CS_OPERATION_RESPONSE,
	KA_REQUEST,
	KA_RESPONSE,
    MB_HANDSHAKE_REQUEST,
    MB_HANDSHAKE_RESPONSE,
    MB_BACKUP_REQUEST,
    MB_BACKUP_RESPONSE
}
