package cs5204.fs.common;

public enum Protocol
{
	CM_HANDSHAKE_REQUEST,
	CM_HANDSHAKE_RESPONSE,
	CM_OPERATION_REQUEST,
	CM_OPERATION_RESPONSE,
	MS_HANDSHAKE_REQUEST,
	MS_HANDSHAKE_RESPONSE,
	MS_COMMIT_REQUEST,
	MS_COMMIT_RESPONSE
}
