package cs5204.fs.common;

public enum Protocol
{
	CM_HANDSHAKE_REQUEST,
	CM_HANDSHAKE_RESPONSE,
	CM_OPERATION_REQUEST,
	CM_OPERATION_RESPONSE,
	MS_HANDSHAKE_REQUEST,
	MS_HANDSHAKE_RESPONSE,
	MS_COMMIT_REQUEST,
	MS_COMMIT_RESPONSE,
	CS_OPERATION_REQUEST,
	CS_OPERATION_RESPONSE,
	KA_REQUEST,
	KA_RESPONSE
}
